services:
  youtube-processor:
    build: ./
    environment:
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - DELIVERY_STREAM_NAME=${DELIVERY_STREAM_NAME}
      - AWS_REGION=${AWS_REGION}
    volumes:
      - ./exportVideos.json:/data/exportVideos.json:ro
    restart: on-failure
    networks:
      - processors

networks:
  processors: